include: package:very_good_analysis/analysis_options.10.0.0.yaml
analyzer:
  errors:
    document_ignores: ignore
  exclude:
    - lib/l10n/*
    - "**/*.g.dart"
    - "**/*.form.dart"
    - lib/app/app.*.dart
linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    unawaited_futures: false
    avoid_catches_without_on_clauses: false